# Copyright (C) 2024 RTE
# SPDX-License-Identifier: Apache-2.0
---
galaxy_info:
  author: "Seapath"
  description: configures the libvirt secret and pool for ceph to use
  license: Apache-2.0
  min_ansible_version: 2.9.10
  platforms:
  - name: Debian
    versions:
    - all
dependencies: []
