# Copyright (C) 2021-2024, RTE (http://www.rte-france.com)
# Copyright (C) 2024 Savoir-faire Linux, Inc.
# SPDX-License-Identifier: Apache-2.0

---

network_systemdnetworkd_team0_network:
  79-team0:
    - Match:
        - Name: "team0"
    - Network:
        - Address: "{{ cluster_ip_addr | default('0') }}/{{ team0subnet | default(24) }}"
  79-team0_0:
    - Match:
        - Name: "{{ team0_0 | default('0') }}"
    - Link:
        - MTUBytes: 1800
  79-team0_1:
    - Match:
        - Name: "{{ team0_1 | default('0') }}"
    - Link:
        - MTUBytes: 1800

...
