# Copyright (C) 2024 RTE
# SPDX-License-Identifier: Apache-2.0

---
- name: Create /etc/cukinia folder
  file:
    path: "/etc/cukinia"
    state: directory
    mode: '0755'

- name: Copy RedHat cukinia tests
  ansible.builtin.copy:
    src: cukinia.conf
    dest: /etc/cukinia/cukinia.conf
    mode: '0644'
- name: Copy RedHat cukinia cluster tests
  ansible.builtin.copy:
    src: cukinia-cluster.conf
    dest: /etc/cukinia/cukinia-cluster.conf
    mode: '0644'
