# Copyright (C) 2025 RTE
# SPDX-License-Identifier: Apache-2.0

---
galaxy_info:
  author: SEAPATH Team
  description: Control node registry management for disconnected environments
  company: RTE
  license: Apache-2.0
  min_ansible_version: "2.10"
  platforms:
    - name: EL
      versions:
        - all
    - name: Debian
      versions:
        - all
  galaxy_tags:
    - seapath
    - registry
    - containers
    - offline
    - disconnected

dependencies: []
