---
# handlers for ansible-role-systemd-networkd

- name: Restart udev
  service:
    name: "{{ network_systemdnetworkd_service_name_udev }}"
    state: restarted

- name: Reload systemd-networkd
  service:
    name: systemd-networkd
    state: reloaded
  when: network_systemdnetworkd_apply_config

- name: Check reboot
  set_fact:
    need_reboot: true
  when: not network_systemdnetworkd_apply_config
