# Copyright (C) 2025 RTE
# SPDX-License-Identifier: Apache-2.0

---
cephadm_release: "20.2.0"
cephadm_release_name: "tentacle"
cephadm_downloadbinary: false
cephadm_installbinary: false
cephadm_installrepo: false
cephadm_installcommon: false
cephadm_pullimages: false

# Registry configuration (for disconnected mode)
cephadm_registry_url: ""
cephadm_registry_username: ""
cephadm_registry_password: ""
