# Copyright (C) 2024 RTE
# SPDX-License-Identifier: Apache-2.0

---
- include_vars: "{{ seapath_distro }}.yml"

- name: Populate service facts
  service_facts:
- name: stop and disable systemd-timesyncd if it exists
  service:
    name: "systemd-timesyncd"
    state: stopped
    enabled: false
  when: "'systemd-timesyncd.service' in services"
- name: Create timemaster configuration
  template:
    src: timemaster.conf.j2
    dest: "{{ path_timemaster_conf }}"
  register: timemasterconf1
- name: comment pool configuration in chrony.conf
  replace:
    path: "{{ path_chrony_conf }}"
    regexp: '^(pool .*)'
    replace: '#\1'
  register: timemasterconf2
- name: Create timemaster.service.d directory
  file:
    path: /etc/systemd/system/timemaster.service.d/
    state: directory
    owner: root
    group: root
    mode: 0755
- name: Copy timemaster.service overide
  template:
    src: timemaster.service.j2
    dest: /etc/systemd/system/timemaster.service.d/override.conf
  register: timemasterconf3
- name: Enable timemaster
  service:
    name: "timemaster"
    enabled: true
- name: restart timemaster if necessary
  service:
    name: "timemaster"
    state: restarted
    enabled: true
    daemon_reload: true
  when:
    - timemasterconf1.changed or timemasterconf2.changed or timemasterconf3.changed
- name: stop and disable chrony
  service:
    name: "{{ service_name_chrony }}"
    state: stopped
    enabled: false
