# Copyright (C) 2024 RTE
# SPDX-License-Identifier: Apache-2.0
---
galaxy_info:
  author: "Seapath"
  description: applies the SEAPATH prerequisites for any Debian physical machine (hypervisor, observer, or standalone)
  license: Apache-2.0
  min_ansible_version: 2.9.10
  platforms:
  - name: CentOS
    versions:
    - all
dependencies: []

