# Copyright (C) 2023 Savoir-faire Linux, Inc.
# SPDX-License-Identifier: Apache-2.0

# This roles recover Ci machine info for openlab

---
- name: Create temporary test directory
  tempfile:
    state: directory
  register: ci_yocto_tmp_test_dir
- name: Execute script
  script: get_system_info.py '{{ ci_yocto_tmp_test_dir.path }}/system_info.adoc'
- name: Fetch results
  fetch:
    src: '{{ ci_yocto_tmp_test_dir.path }}/system_info.adoc'
    dest: "{{ cukinia_test_prefix | default('..') }}/system_info_{{ inventory_hostname }}.adoc"
    flat: yes
...
