# Copyright (C) 2024 RTE
# SPDX-License-Identifier: Apache-2.0
---
galaxy_info:
  author: "Seapath"
  description: deploys Guests in cluster mode
  license: Apache-2.0
  min_ansible_version: 2.9.10
  platforms:
  - name: Linux
    versions:
    - all
dependencies: []
