# Copyright (C) 2021, RTE (http://www.rte-france.com)
# SPDX-License-Identifier: Apache-2.0

---
- name: Wait all VM have finish to boot
  hosts: VMs
  gather_facts: no
  tasks:
      - name: Wait for VM to be online
        wait_for_connection:
- name: Stop the DHCP server
  hosts: localhost
  tasks:
      - name: Stop ci_dhcp_vm container
        docker_container:
            state: "stopped"
            name: "ci_dhcp_vm"

- name: Configure Network
  hosts: VMs
  vars_files:
      - ../vars/network_vars.yml
  roles:
      - systemd_networkd

- name: Apply network configuration
  hosts: VMs
  tasks:
      - name: Restart systemd-networkd
        ansible.builtin.systemd:
            name: systemd-networkd
            state: restarted

- name: Configure hosts and hostname
  hosts: VMs
  tasks:
      - name: Set hostname
        hostname:
            name: "{{ inventory_hostname }}"
            use: systemd
      - name: Build hosts file
        lineinfile:
            dest: /etc/hosts
            regexp: '.*{{ item }}$'
            line: "{{ hostvars[item].ip_addr }} {{item}}"
            state: present
        when: hostvars[item].ip_addr is defined
        loop: "{{ groups['cluster_machines'] }}"
      - name: Add rbd in hosts file
        replace:
            path: /etc/hosts
            regexp: '^{{ ip_addr }} {{ inventory_hostname }}$'
            replace: '{{ ip_addr }} rbd {{ inventory_hostname }}'
