# Copyright (C) 2024 Savoir-faire Linux, Inc
# SPDX-License-Identifier: Apache-2.0

# Run script to send SV from pcap file

- hosts: publisher_machines
  name: Run Test
  gather_facts: false
  become: true
  vars:
    - home: /root
    - script_name: "ci_publish_sv.sh"
  tasks:
    - name: "Prepare Publisher"
      file:
        path: "{{ item }}"
        state: directory
      loop:
          - "{{ home }}/tests"
          - "{{ home }}/tests/results"
          - "{{ home }}/tests/pcaps"
    - name: "Copy pcap file on publisher"
      copy:
        src: "{{ pcap_file }}"
        dest: "{{ home }}/tests/pcaps"
    - name: "test script ansible"
      script: "{{ script_name }} {{ pcap_file }} {{ home }}/tests"
