# Copyright (C) 2021, RTE (http://www.rte-france.com)
# SPDX-License-Identifier: Apache-2.0
# This Ansible playbook is used to ensure that the 4 VMs created on an
# hypervisor have started correctly.
---
- name: Test VM status
  hosts: hypervisors
  vars:
      -  any_errors_fatal: false
  tasks:
  - name: Test VM state
    shell: crm status
    register: vm_status
    until: |
      vm_status.stdout.find("FAILED") != -1 or
      vm_status.stdout.find("Stopped") != -1 or
      vm_status.stdout.count("Started") == 4
    retries: 20
    delay: 2
    failed_when: |
      vm_status.stdout.find("FAILED") != -1 or
      vm_status.stdout.find("Stopped") != -1
