# Copyright (C) 2022, RTE (http://www.rte-france.com)
# Copyright (C) 2024 Savoir-faire Linux, Inc.
# SPDX-License-Identifier: Apache-2.0

# This playbook adds and configures the livemigration user. This user is used by libvirt
# to migrate VM from a host to an other without halting it.

---
- name: Create livemigration user
  hosts: hypervisors:&cluster_machines
  gather_facts: true
  become: true
  roles:
    - add_livemigration_user
