---
# Copyright (C) 2021, RTE (http://www.rte-france.com)
# SPDX-License-Identifier: Apache-2.0

# This playbook will configure a static IP. It works with the flash PXE image.

- name: Configure a static IP
  hosts: pxe_machines
  vars:
      ipaddr: "{{ static_ip }}"
      mask: "{{ subnet | default(24) }}"
      interface: "{{ network_interface | default(eth0) }}"
  tasks:
      - name: Mount the file system
        shell:
            cmd: mount /dev/disk/by-label/platform /mnt
            warn: no
      - name: Install the systemd-networkd configuration file
        template:
            dest: /mnt/etc/systemd/network/000-static_ip.network
            src: ../templates/000-static-ip.network.j2
      - name: Umount the file system
        shell:
            cmd: umount /mnt
            warn: no
