- name: remove /etc/systemd/system/systemd-networkd-wait-online.service file
  hosts: cluster_machines
  tasks:
    - name: /etc/systemd/system/systemd-networkd-wait-online.service absent
      file:
        path: /etc/systemd/system/systemd-networkd-wait-online.service
        state: absent
- name: UEFI Create slots
  hosts: cluster_machines
  tasks:
    - name: run bash script to create UEFI slots
      script: |
          ../scripts/create_efi_boot_slots.sh {{ main_disk }}
- import_playbook: cluster_setup_network.yaml
- import_playbook: cluster_setup_ceph.yaml
- import_playbook: cluster_setup_libvirt.yaml
- import_playbook: cluster_setup_keys.yaml
- import_playbook: cluster_setup_ha.yaml
- name: config elastic metricbeat
  hosts: cluster_machines
  tasks:
    - name: lineinfile in hosts file for logstash_seapath
      lineinfile:
        dest: /etc/hosts
        line: "{{ logstash_server_ip }} logstash_seapath"
        state: present
- name: config MSMTP
  hosts: cluster_machines
  tasks:
    - name: add MSMSTP config file
      template:
        dest: /etc/msmtprc
        src: ../templates/msmtprc.j2
        mode: '0644'
- name: Add pacemaker alerting and monitoring
  hosts: cluster_machines
  tasks:
      - name: add SNMP alerting
        shell: crm configure alert alert-1 "/var/lib/pacemaker/alert_snmp.sh" meta timestamp-format="%Y-%m-%d,%H:%M:%S.%01N" to "{{ snmp_trap_server }}"
        run_once: true
        when: pass is undefined or pass!="second"
      - name: add SMTP alerting
        shell: crm configure alert alert-2 "/var/lib/pacemaker/alert_smtp.sh" to "{{ email_alert_recipient }}"
        run_once: true
        when: pass is undefined or pass!="second"

- name: configure hawkbit
  hosts: cluster_machines
  tasks:
    - name: change ip in hawkbit conf file
      replace:
        path: /etc/sysconfig/swupdate_hawkbit.conf
        regexp: '^HAWKBIT_SERVER_URL=.*$'
        replace: 'HAWKBIT_SERVER_URL={{ hawkbit_ip_addr }}'
      when: hawkbit_ip_addr is defined
- name: Restart all hosts
  hosts: cluster_machines
  tasks:
    - name: Restart
      reboot:
    - name: Wait for host to be online
      wait_for_connection:

