# Copyright (C) 2024 Savoir-faire Linux, Inc.
# SPDX-License-Identifier: Apache-2.0
# This file will execute ansible-lint on the debian-main branch every saturday
# This ensure the main branch is always linted properly
# A badge is derived from this workflow

name: Ansible Lint

on:
  schedule:
    - cron: '30 22 * * 6'

jobs:
  call-workflow:
    uses: ./.github/workflows/ansible-lint.yml
